name: Resume review
description: Please review my resume in a live stream
labels: ["review my resume"]
body:
  - type: markdown
    attributes:
      value: |
       **Remove all personal data, otherwise the resume will be deleted.**
       Items we can review on a live stream:

       - GitHub profile
       - Open source project
       - Portfolio
       - Resume
  - type: input
    id: link
    attributes:
      label: Resume link
      placeholder: "https://drive.google.com/file/d/<file-id>/view"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
       You can also join our Discord community [here](http://discord.pugroups.in)
       Feel free to check out other cool repositories of the PUG Community [here](https://github.com/PUGroup)
