name: Open Source Project Review
description: Please review my project on a livestream
title: "[REVIEW] <project name here>"
labels: [open source review, live stream review]
body:
  - type: markdown
    attributes:
      value: "Your project doesn't have to be hosted at GitHub, it can also be on GitLab or hosted in other VCS."
  - type: markdown
    attributes:
      value: |
       Items we can review on a live stream or meetups:

       - GitHub profile
       - Open source project
       - Portfolio
  - type: input
    id: link
    attributes:
      label: Project link
      placeholder: https://github.com/<your-username>/<project-name>
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
       You can also join our Discord community [here](http://discord.pugroups.in)
       Feel free to check out other cool repositories of the PUG Community [here](https://github.com/PUGroup)
